# permissions for end users to view ipranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iprange-viewer-role
rules:
- apiGroups:
  - allocator.k8s.io
  resources:
  - ipranges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - allocator.k8s.io
  resources:
  - ipranges/status
  verbs:
  - get
